//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace INTRASTAT {
    using System.Xml.Serialization;
   using System.IO;
   using System.Xml;
   using System;


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/ir002a")]
    [System.Xml.Serialization.XmlRootAttribute("IR002A", Namespace="http://apisit.hr/b28/inst/ed/2011/ir002a", IsNullable=false)]
    public partial class IR002AType {
        
      #region Serialize/Deserialize

      private static System.Xml.Serialization.XmlSerializer serializer;
      private static System.Xml.Serialization.XmlSerializer Serializer
      {
         get
         {
            if((serializer == null))
            {
               serializer = new System.Xml.Serialization.XmlSerializer(typeof(IR002AType));
            }
            return serializer;
         }
      }

      /// <summary>
      /// Serializes current IR002AType object into an XML IR002AType
      /// </summary>
      /// <returns>string XML value</returns>
      public virtual string Serialize(System.Text.Encoding encoding)
      {
         System.IO.StreamReader streamReader = null;
         System.IO.MemoryStream memoryStream = null;
         string xmlString = "";

         try
         {
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings()
            {
               Encoding = encoding,
               Indent = true, // byQ 
               IndentChars = "   ", // byQ 
            };

            memoryStream = new System.IO.MemoryStream();

            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            streamReader = new System.IO.StreamReader(memoryStream);
            xmlString = streamReader.ReadToEnd();

            return xmlString;
         }
         finally
         {
            if((streamReader != null))
            {
               streamReader.Dispose();
            }
            if((memoryStream != null))
            {
               memoryStream.Dispose();
            }
         }
      }

      public virtual string Serialize()
      {
         return Serialize(/*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM);
      }

      /// <summary>
      /// Deserializes workflow markup into an IR002AType object
      /// </summary>
      /// <param name="xml">string workflow markup to deserialize</param>
      /// <param name="obj">Output IR002AType object</param>
      /// <param name="exception">output Exception value if deserialize failed</param>
      /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
      public static bool Deserialize(string xml, out IR002AType obj, out System.Exception exception)
      {
         exception = null;
         obj = default(IR002AType);
         try
         {
            obj = Deserialize(xml);
            return true;
         }
         catch(System.Exception ex)
         {
            exception = ex;
            return false;
         }
      }

      public static bool Deserialize(string xml, out IR002AType obj)
      {
         System.Exception exception = null;
         return Deserialize(xml, out obj, out exception);
      }

      public static IR002AType Deserialize(string xml)
      {
         System.IO.StringReader stringReader = null;
         try
         {
            stringReader = new System.IO.StringReader(xml);
            return ((IR002AType)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
         }
         finally
         {
            if((stringReader != null))
            {
               stringReader.Dispose();
            }
         }
      }

      /// <summary>
      /// Serializes current IR002AType object into file
      /// </summary>
      /// <param name="fileName">full path of outupt xml file</param>
      /// <param name="exception">output Exception value if failed</param>
      /// <returns>true if can serialize and save into file; otherwise, false</returns>
      public virtual string SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
      {
         exception = null;
         try
         {
            return SaveToFile(fileName, encoding);
            //return true;
         }
         catch(System.Exception e)
         {
            exception = e;
            return "";
         }
      }

      public virtual string SaveToFile(string fileName, out System.Exception exception)
      {
         return SaveToFile(fileName, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM, out exception);
      }

      public virtual string SaveToFile(string fileName)
      {
         return SaveToFile(fileName, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM);
      }

      public virtual string SaveToFile(string fileName, System.Text.Encoding encoding)
      {
         string xmlString = "";

         System.IO.StreamWriter streamWriter = null;
         try
         {
            xmlString = Serialize(encoding);
            streamWriter = new System.IO.StreamWriter(fileName, false, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM);
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
         }
         finally
         {
            if((streamWriter != null))
            {
               streamWriter.Dispose();
            }
         }

         return xmlString;
      }

      public bool VvSaveToFile(string xmlString, string fileName, System.Text.Encoding encoding)
      {
         System.IO.StreamWriter streamWriter = null;

         bool isOK = true;
         try
         {
            streamWriter = new System.IO.StreamWriter(fileName, false, encoding /*Encoding.UTF8*/ /*ZXC.VvUTF8Encoding_noBOM*/);
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
         }
         catch(Exception)
         {
            isOK = false;
         }
         finally
         {
            if((streamWriter != null))
            {
               streamWriter.Dispose();
            }
         }

         return isOK;
      }

      /// <summary>
      /// Deserializes xml markup from file into an IR002AType object
      /// </summary>
      /// <param name="fileName">string xml file to load and deserialize</param>
      /// <param name="the_eRacun">Output IR002AType object</param>
      /// <param name="exception">output Exception value if deserialize failed</param>
      /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
      public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out IR002AType the_eRacun, out System.Exception exception)
      {
         exception = null;
         the_eRacun = default(IR002AType);
         try
         {
            the_eRacun = LoadFromFile(fileName, encoding);
            return true;
         }
         catch(System.Exception ex)
         {
            exception = ex;
            return false;
         }
      }

      public static bool LoadFromFile(string fileName, out IR002AType the_eRacun, out System.Exception exception)
      {
         return LoadFromFile(fileName, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM, out the_eRacun, out exception);
      }

      public static bool LoadFromFile(string fileName, out IR002AType the_eRacun)
      {
         System.Exception exception = null;
         return LoadFromFile(fileName, out the_eRacun, out exception);
      }

      //public static IR002AType LoadFromFile(string fileName)
      //{
      //   return LoadFromFile(fileName, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM);
      //}

      public static IR002AType LoadFromFile(string fileName, System.Text.Encoding encoding)
      {
         System.IO.FileStream file = null;
         System.IO.StreamReader sr = null;
         try
         {
            file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new System.IO.StreamReader(file, encoding);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
         }
         finally
         {
            if((file != null))
            {
               file.Dispose();
            }
            if((sr != null))
            {
               sr.Dispose();
            }
         }
      }

      #endregion

        private EnvelopeType envelopeField;
        
        /// <remarks/>
        public EnvelopeType Envelope {
            get {
                return this.envelopeField;
            }
            set {
                this.envelopeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/ir002a")]
    public partial class EnvelopeType {
        
        private HeaderType headerField;
        
        private DeclarationType declarationField;
        
        /// <remarks/>
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public DeclarationType Declaration {
            get {
                return this.declarationField;
            }
            set {
                this.declarationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/ir002a")]
    public partial class HeaderType {
        
        private short flowOfGoodsField;
        
        private PSIType pSIField;
        
        private string referencePeriodField;
        
        private DeclarantType declarantField;
        
        private ReportTypeType reportTypeField;
        
        private System.DateTime reportDateField;
        
        /// <remarks/>
        public short FlowOfGoods {
            get {
                return this.flowOfGoodsField;
            }
            set {
                this.flowOfGoodsField = value;
            }
        }
        
        /// <remarks/>
        public PSIType PSI {
            get {
                return this.pSIField;
            }
            set {
                this.pSIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
        public string ReferencePeriod {
            get {
                return this.referencePeriodField;
            }
            set {
                this.referencePeriodField = value;
            }
        }
        
        /// <remarks/>
        public DeclarantType Declarant {
            get {
                return this.declarantField;
            }
            set {
                this.declarantField = value;
            }
        }
        
        /// <remarks/>
        public ReportTypeType ReportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReportDate {
            get {
                return this.reportDateField;
            }
            set {
                this.reportDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/complexTypes")]
    public partial class PSIType {
        
        private PSIIdType pSIIdField;
        
        private string pSINameField;
        
        private string pSIAddressField;
        
        /// <remarks/>
        public PSIIdType PSIId {
            get {
                return this.pSIIdField;
            }
            set {
                this.pSIIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string PSIName {
            get {
                return this.pSINameField;
            }
            set {
                this.pSINameField = value;
            }
        }
        
        /// <remarks/>
        public string PSIAddress {
            get {
                return this.pSIAddressField;
            }
            set {
                this.pSIAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/complexTypes")]
    public partial class PSIIdType {
        
        private PSICountryCodeType pSICountryCodeField;
        
        private string pSININumberField;
        
        /// <remarks/>
        public PSICountryCodeType PSICountryCode {
            get {
                return this.pSICountryCodeField;
            }
            set {
                this.pSICountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PSININumber {
            get {
                return this.pSININumberField;
            }
            set {
                this.pSININumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/baseTypes")]
    public enum PSICountryCodeType {
        
        /// <remarks/>
        HR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/complexTypes")]
    public partial class NatureOfTransactionType {
        
        private short natureOfTransactionACodeField;
        
        private short natureOfTransactionBCodeField;
        
        private bool natureOfTransactionBCodeFieldSpecified;
        
        /// <remarks/>
        public short NatureOfTransactionACode {
            get {
                return this.natureOfTransactionACodeField;
            }
            set {
                this.natureOfTransactionACodeField = value;
            }
        }
        
        /// <remarks/>
        public short NatureOfTransactionBCode {
            get {
                return this.natureOfTransactionBCodeField;
            }
            set {
                this.natureOfTransactionBCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NatureOfTransactionBCodeSpecified {
            get {
                return this.natureOfTransactionBCodeFieldSpecified;
            }
            set {
                this.natureOfTransactionBCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/complexTypes")]
    public partial class DeliveryTermsType {
        
        private string deliveryTermsCodeField;
        
        private short placeOfDeliveryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string DeliveryTermsCode {
            get {
                return this.deliveryTermsCodeField;
            }
            set {
                this.deliveryTermsCodeField = value;
            }
        }
        
        /// <remarks/>
        public short PlaceOfDeliveryCode {
            get {
                return this.placeOfDeliveryCodeField;
            }
            set {
                this.placeOfDeliveryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/ir002a")]
    public partial class ItemType {
        
        private uint itemNrField;
        
        private string vATNumberField;
        
        private string cN8CodeField;
        
        private string goodsDescriptionField;
        
        private string destinationCountryCodeField;
        
        private DeliveryTermsType deliveryTermsField;
        
        private NatureOfTransactionType natureOfTransactionField;
        
        private short transportModeField;
        
        private string countryOfOriginCodeField;
        
        private decimal netWeightField;
        
        private bool netWeightFieldSpecified;
        
        private decimal quantityInSUField;
        
        private bool quantityInSUFieldSpecified;
        
        private decimal invoicedAmountField;
        
        /// <remarks/>
        public uint ItemNr {
            get {
                return this.itemNrField;
            }
            set {
                this.itemNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string VATNumber {
            get {
                return this.vATNumberField;
            }
            set {
                this.vATNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string CN8Code {
            get {
                return this.cN8CodeField;
            }
            set {
                this.cN8CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string GoodsDescription {
            get {
                return this.goodsDescriptionField;
            }
            set {
                this.goodsDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string DestinationCountryCode {
            get {
                return this.destinationCountryCodeField;
            }
            set {
                this.destinationCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryTermsType DeliveryTerms {
            get {
                return this.deliveryTermsField;
            }
            set {
                this.deliveryTermsField = value;
            }
        }
        
        /// <remarks/>
        public NatureOfTransactionType NatureOfTransaction {
            get {
                return this.natureOfTransactionField;
            }
            set {
                this.natureOfTransactionField = value;
            }
        }
        
        /// <remarks/>
        public short TransportMode {
            get {
                return this.transportModeField;
            }
            set {
                this.transportModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string CountryOfOriginCode {
            get {
                return this.countryOfOriginCodeField;
            }
            set {
                this.countryOfOriginCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal NetWeight {
            get {
                return this.netWeightField;
            }
            set {
                this.netWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NetWeightSpecified {
            get {
                return this.netWeightFieldSpecified;
            }
            set {
                this.netWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal QuantityInSU {
            get {
                return this.quantityInSUField;
            }
            set {
                this.quantityInSUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityInSUSpecified {
            get {
                return this.quantityInSUFieldSpecified;
            }
            set {
                this.quantityInSUFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal InvoicedAmount {
            get {
                return this.invoicedAmountField;
            }
            set {
                this.invoicedAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/ir002a")]
    public partial class DeclarationType {
        
        private ItemType[] itemField;
        
        private uint totalItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public ItemType[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public uint TotalItems {
            get {
                return this.totalItemsField;
            }
            set {
                this.totalItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/complexTypes")]
    public partial class DeclarantIdType {
        
        private string declarantCountryCodeField;
        
        private string declarantNINumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string DeclarantCountryCode {
            get {
                return this.declarantCountryCodeField;
            }
            set {
                this.declarantCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string DeclarantNINumber {
            get {
                return this.declarantNINumberField;
            }
            set {
                this.declarantNINumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/complexTypes")]
    public partial class DeclarantType {
        
        private DeclarantIdType declarantIdField;
        
        private string declarantNameField;
        
        private string declarantAddressField;
        
        private string declarantCountryField;
        
        /// <remarks/>
        public DeclarantIdType DeclarantId {
            get {
                return this.declarantIdField;
            }
            set {
                this.declarantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string DeclarantName {
            get {
                return this.declarantNameField;
            }
            set {
                this.declarantNameField = value;
            }
        }
        
        /// <remarks/>
        public string DeclarantAddress {
            get {
                return this.declarantAddressField;
            }
            set {
                this.declarantAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string DeclarantCountry {
            get {
                return this.declarantCountryField;
            }
            set {
                this.declarantCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apisit.hr/b28/inst/ed/2011/baseTypes")]
    public enum ReportTypeType {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        B,
    }
}
