//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PAIN_001_001_09
{

   using System.IO;
   using System.Xml;
   using PAIN_001_001_03;

   // 
   // This source code was auto-generated by xsd, Version=4.6.1590.0.
   // 


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09", IsNullable = false)]
   public partial class Document
   {

      private CustomerCreditTransferInitiationV09 cstmrCdtTrfInitnField;

      /// <remarks/>
      public CustomerCreditTransferInitiationV09 CstmrCdtTrfInitn
      {
         get
         {
            return this.cstmrCdtTrfInitnField;
         }
         set
         {
            this.cstmrCdtTrfInitnField = value;
         }
      }

      #region Ovu regiju kopipejstas rucno u nove code from xsd ... ex 'Serialize/Deserialize'

      public Document()
      {
         this.cstmrCdtTrfInitnField = new CustomerCreditTransferInitiationV09();
      }

      private static System.Xml.Serialization.XmlSerializer serializer;
      private static System.Xml.Serialization.XmlSerializer Serializer
      {
         get
         {
            if((serializer == null))
            {
               serializer = new System.Xml.Serialization.XmlSerializer(typeof(Document));
            }
            return serializer;
         }
      }
      /// <summary>
      /// Serializes current Document object into an XML document
      /// </summary>
      /// <returns>string XML value</returns>
      public virtual string Serialize(System.Text.Encoding encoding)
      {
         System.IO.StreamReader streamReader = null;
         System.IO.MemoryStream memoryStream = null;
         try
         {
            memoryStream = new System.IO.MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            xmlWriterSettings.Encoding = encoding;

            xmlWriterSettings.Indent      = true ; // byQ 
            xmlWriterSettings.IndentChars = "   "; // byQ 

            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
         }
         finally
         {
            if((streamReader != null))
            {
               streamReader.Dispose();
            }
            if((memoryStream != null))
            {
               memoryStream.Dispose();
            }
         }
      }

      public virtual string Serialize()
      {
         return Serialize(/*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM);
      }

      /// <summary>
      /// Deserializes workflow markup into an Document object
      /// </summary>
      /// <param name="xml">string workflow markup to deserialize</param>
      /// <param name="obj">Output Document object</param>
      /// <param name="exception">output Exception value if deserialize failed</param>
      /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
      public static bool Deserialize(string xml, out Document obj, out System.Exception exception)
      {
         exception = null;
         obj = default(Document);
         try
         {
            obj = Deserialize(xml);
            return true;
         }
         catch(System.Exception ex)
         {
            exception = ex;
            return false;
         }
      }

      public static bool Deserialize(string xml, out Document obj)
      {
         System.Exception exception = null;
         return Deserialize(xml, out obj, out exception);
      }

      public static Document Deserialize(string xml)
      {
         System.IO.StringReader stringReader = null;
         try
         {
            stringReader = new System.IO.StringReader(xml);
            return ((Document)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
         }
         finally
         {
            if((stringReader != null))
            {
               stringReader.Dispose();
            }
         }
      }

      /// <summary>
      /// Serializes current Document object into file
      /// </summary>
      /// <param name="fileName">full path of outupt xml file</param>
      /// <param name="exception">output Exception value if failed</param>
      /// <returns>true if can serialize and save into file; otherwise, false</returns>
      public virtual bool SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
      {
         exception = null;
         try
         {
            SaveToFile(fileName, encoding);
            return true;
         }
         catch(System.Exception e)
         {
            exception = e;
            return false;
         }
      }

      public virtual bool SaveToFile(string fileName, out System.Exception exception)
      {
         return SaveToFile(fileName, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM, out exception);
      }

      public virtual void SaveToFile(string fileName)
      {
         SaveToFile(fileName, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM);
      }

      public virtual void SaveToFile(string fileName, System.Text.Encoding encoding)
      {
         System.IO.StreamWriter streamWriter = null;
         try
         {
            string xmlString = Serialize(encoding);
            streamWriter = new System.IO.StreamWriter(fileName, false, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM);
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
         }
         finally
         {
            if((streamWriter != null))
            {
               streamWriter.Dispose();
            }
         }
      }

      /// <summary>
      /// Deserializes xml markup from file into an Document object
      /// </summary>
      /// <param name="fileName">string xml file to load and deserialize</param>
      /// <param name="obj">Output Document object</param>
      /// <param name="exception">output Exception value if deserialize failed</param>
      /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
      public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out Document obj, out System.Exception exception)
      {
         exception = null;
         obj = default(Document);
         try
         {
            obj = LoadFromFile(fileName, encoding);
            return true;
         }
         catch(System.Exception ex)
         {
            exception = ex;
            return false;
         }
      }

      public static bool LoadFromFile(string fileName, out Document obj, out System.Exception exception)
      {
         return LoadFromFile(fileName, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM, out obj, out exception);
      }

      public static bool LoadFromFile(string fileName, out Document obj)
      {
         System.Exception exception = null;
         return LoadFromFile(fileName, out obj, out exception);
      }

      public static Document LoadFromFile(string fileName)
      {
         return LoadFromFile(fileName, /*Encoding.UTF8*/ ZXC.VvUTF8Encoding_noBOM);
      }

      public static Document LoadFromFile(string fileName, System.Text.Encoding encoding)
      {
         System.IO.FileStream file = null;
         System.IO.StreamReader sr = null;
         try
         {
            file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new System.IO.StreamReader(file, encoding);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
         }
         finally
         {
            if((file != null))
            {
               file.Dispose();
            }
            if((sr != null))
            {
               sr.Dispose();
            }
         }
      }
      #endregion
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class CustomerCreditTransferInitiationV09
   {

      private GroupHeader85 grpHdrField;

      private PaymentInstruction30[] pmtInfField;

      /// <remarks/>
      public GroupHeader85 GrpHdr
      {
         get
         {
            return this.grpHdrField;
         }
         set
         {
            this.grpHdrField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("PmtInf")]
      public PaymentInstruction30[] PmtInf
      {
         get
         {
            return this.pmtInfField;
         }
         set
         {
            this.pmtInfField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class GroupHeader85
   {

      private string msgIdField;

      private System.DateTime creDtTmField;

      private string nbOfTxsField;

      private decimal ctrlSumField;

      private PartyIdentification135_2 initgPtyField;

      /// <remarks/>
      public string MsgId
      {
         get
         {
            return this.msgIdField;
         }
         set
         {
            this.msgIdField = value;
         }
      }

      /// <remarks/>
      public System.DateTime CreDtTm
      {
         get
         {
            return this.creDtTmField;
         }
         set
         {
            this.creDtTmField = value;
         }
      }

      /// <remarks/>
      public string NbOfTxs
      {
         get
         {
            return this.nbOfTxsField;
         }
         set
         {
            this.nbOfTxsField = value;
         }
      }

      /// <remarks/>
      public decimal CtrlSum
      {
         get
         {
            return this.ctrlSumField;
         }
         set
         {
            this.ctrlSumField = value;
         }
      }

      /// <remarks/>
      public PartyIdentification135_2 InitgPty
      {
         get
         {
            return this.initgPtyField;
         }
         set
         {
            this.initgPtyField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class PartyIdentification135_2
   {

      private string nmField;

      private Party38Choice idField;

      /// <remarks/>
      public string Nm
      {
         get
         {
            return this.nmField;
         }
         set
         {
            this.nmField = value;
         }
      }

      /// <remarks/>
      public Party38Choice Id
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class Party38Choice
   {

      private object itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(OrganisationIdentification29))]
      [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentification13))]
      public object Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class OrganisationIdentification29
   {

      private object itemField;

      private ItemChoiceType1 itemElementNameField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
      [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
      [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericOrganisationIdentification1))]
      [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
      public object Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public ItemChoiceType1 ItemElementName
      {
         get
         {
            return this.itemElementNameField;
         }
         set
         {
            this.itemElementNameField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class GenericOrganisationIdentification1
   {

      private string idField;

      private OrganisationIdentificationSchemeName1Choice schmeNmField;

      private string issrField;

      /// <remarks/>
      public string Id
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }

      /// <remarks/>
      public OrganisationIdentificationSchemeName1Choice SchmeNm
      {
         get
         {
            return this.schmeNmField;
         }
         set
         {
            this.schmeNmField = value;
         }
      }

      /// <remarks/>
      public string Issr
      {
         get
         {
            return this.issrField;
         }
         set
         {
            this.issrField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class OrganisationIdentificationSchemeName1Choice
   {

      private string itemField;

      private ItemChoiceType itemElementNameField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
      [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
      [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
      public string Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public ItemChoiceType ItemElementName
      {
         get
         {
            return this.itemElementNameField;
         }
         set
         {
            this.itemElementNameField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09", IncludeInSchema = false)]
   public enum ItemChoiceType
   {

      /// <remarks/>
      Cd,

      /// <remarks/>
      Prtry,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class CreditorReferenceType1Choice
   {

      private DocumentType3Code cdField;

      /// <remarks/>
      public DocumentType3Code Cd
      {
         get
         {
            return this.cdField;
         }
         set
         {
            this.cdField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public enum DocumentType3Code
   {

      /// <remarks/>
      SCOR,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class CreditorReferenceType2
   {

      private CreditorReferenceType1Choice cdOrPrtryField;

      private string issrField;

      /// <remarks/>
      public CreditorReferenceType1Choice CdOrPrtry
      {
         get
         {
            return this.cdOrPrtryField;
         }
         set
         {
            this.cdOrPrtryField = value;
         }
      }

      /// <remarks/>
      public string Issr
      {
         get
         {
            return this.issrField;
         }
         set
         {
            this.issrField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class CreditorReferenceInformation2
   {

      private CreditorReferenceType2 tpField;

      private string refField;

      /// <remarks/>
      public CreditorReferenceType2 Tp
      {
         get
         {
            return this.tpField;
         }
         set
         {
            this.tpField = value;
         }
      }

      /// <remarks/>
      public string Ref
      {
         get
         {
            return this.refField;
         }
         set
         {
            this.refField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class StructuredRemittanceInformation16
   {

      private CreditorReferenceInformation2 cdtrRefInfField;

      private string addtlRmtInfField;

      /// <remarks/>
      public CreditorReferenceInformation2 CdtrRefInf
      {
         get
         {
            return this.cdtrRefInfField;
         }
         set
         {
            this.cdtrRefInfField = value;
         }
      }

      /// <remarks/>
      public string AddtlRmtInf
      {
         get
         {
            return this.addtlRmtInfField;
         }
         set
         {
            this.addtlRmtInfField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class RemittanceInformation16
   {

      private object itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Strd", typeof(StructuredRemittanceInformation16))]
      [System.Xml.Serialization.XmlElementAttribute("Ustrd", typeof(string))]
      public object Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class Purpose2Choice
   {

      private string cdField;

      /// <remarks/>
      public string Cd
      {
         get
         {
            return this.cdField;
         }
         set
         {
            this.cdField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class GenericAccountIdentification1
   {

      private string idField;

      /// <remarks/>
      public string Id
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class AccountIdentification4Choice_2
   {

      private object itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("IBAN", typeof(string))]
      [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericAccountIdentification1))]
      public object Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class CashAccount38Cdtr
   {

      private AccountIdentification4Choice_2 idField;

      /// <remarks/>
      public AccountIdentification4Choice_2 Id
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class ClearingSystemMemberIdentification2
   {

      private string mmbIdField;

      /// <remarks/>
      public string MmbId
      {
         get
         {
            return this.mmbIdField;
         }
         set
         {
            this.mmbIdField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class FinancialInstitutionIdentification18CdtrAgt
   {

      private string bICFIField;

      private ClearingSystemMemberIdentification2 clrSysMmbIdField;

      private string nmField;

      private PostalAddress24 pstlAdrField;

      /// <remarks/>
      public string BICFI
      {
         get
         {
            return this.bICFIField;
         }
         set
         {
            this.bICFIField = value;
         }
      }

      /// <remarks/>
      public ClearingSystemMemberIdentification2 ClrSysMmbId
      {
         get
         {
            return this.clrSysMmbIdField;
         }
         set
         {
            this.clrSysMmbIdField = value;
         }
      }

      /// <remarks/>
      public string Nm
      {
         get
         {
            return this.nmField;
         }
         set
         {
            this.nmField = value;
         }
      }

      /// <remarks/>
      public PostalAddress24 PstlAdr
      {
         get
         {
            return this.pstlAdrField;
         }
         set
         {
            this.pstlAdrField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class PostalAddress24
   {

      private string deptField;

      private string subDeptField;

      private string strtNmField;

      private string bldgNbField;

      private string bldgNmField;

      private string flrField;

      private string pstBxField;

      private string roomField;

      private string pstCdField;

      private string twnNmField;

      private string twnLctnNmField;

      private string dstrctNmField;

      private string ctrySubDvsnField;

      private string ctryField;

      private string[] adrLineField;

      /// <remarks/>
      public string Dept
      {
         get
         {
            return this.deptField;
         }
         set
         {
            this.deptField = value;
         }
      }

      /// <remarks/>
      public string SubDept
      {
         get
         {
            return this.subDeptField;
         }
         set
         {
            this.subDeptField = value;
         }
      }

      /// <remarks/>
      public string StrtNm
      {
         get
         {
            return this.strtNmField;
         }
         set
         {
            this.strtNmField = value;
         }
      }

      /// <remarks/>
      public string BldgNb
      {
         get
         {
            return this.bldgNbField;
         }
         set
         {
            this.bldgNbField = value;
         }
      }

      /// <remarks/>
      public string BldgNm
      {
         get
         {
            return this.bldgNmField;
         }
         set
         {
            this.bldgNmField = value;
         }
      }

      /// <remarks/>
      public string Flr
      {
         get
         {
            return this.flrField;
         }
         set
         {
            this.flrField = value;
         }
      }

      /// <remarks/>
      public string PstBx
      {
         get
         {
            return this.pstBxField;
         }
         set
         {
            this.pstBxField = value;
         }
      }

      /// <remarks/>
      public string Room
      {
         get
         {
            return this.roomField;
         }
         set
         {
            this.roomField = value;
         }
      }

      /// <remarks/>
      public string PstCd
      {
         get
         {
            return this.pstCdField;
         }
         set
         {
            this.pstCdField = value;
         }
      }

      /// <remarks/>
      public string TwnNm
      {
         get
         {
            return this.twnNmField;
         }
         set
         {
            this.twnNmField = value;
         }
      }

      /// <remarks/>
      public string TwnLctnNm
      {
         get
         {
            return this.twnLctnNmField;
         }
         set
         {
            this.twnLctnNmField = value;
         }
      }

      /// <remarks/>
      public string DstrctNm
      {
         get
         {
            return this.dstrctNmField;
         }
         set
         {
            this.dstrctNmField = value;
         }
      }

      /// <remarks/>
      public string CtrySubDvsn
      {
         get
         {
            return this.ctrySubDvsnField;
         }
         set
         {
            this.ctrySubDvsnField = value;
         }
      }

      /// <remarks/>
      public string Ctry
      {
         get
         {
            return this.ctryField;
         }
         set
         {
            this.ctryField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
      public string[] AdrLine
      {
         get
         {
            return this.adrLineField;
         }
         set
         {
            this.adrLineField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class BranchAndFinancialInstitutionIdentification6CdtrAgt
   {

      private FinancialInstitutionIdentification18CdtrAgt finInstnIdField;

      /// <remarks/>
      public FinancialInstitutionIdentification18CdtrAgt FinInstnId
      {
         get
         {
            return this.finInstnIdField;
         }
         set
         {
            this.finInstnIdField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class ActiveOrHistoricCurrencyAndAmount
   {

      private string ccyField;

      private decimal valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Ccy
      {
         get
         {
            return this.ccyField;
         }
         set
         {
            this.ccyField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public decimal Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class AmountType4Choice
   {

      private ActiveOrHistoricCurrencyAndAmount instdAmtField;

      /// <remarks/>
      public ActiveOrHistoricCurrencyAndAmount InstdAmt
      {
         get
         {
            return this.instdAmtField;
         }
         set
         {
            this.instdAmtField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class PaymentTypeInformation26CdtTrfTxInf
   {

      private ServiceLevel8Choice svcLvlField;

      private LocalInstrument2Choice lclInstrmField;

      private CategoryPurpose1Choice ctgyPurpField;

      /// <remarks/>
      public ServiceLevel8Choice SvcLvl
      {
         get
         {
            return this.svcLvlField;
         }
         set
         {
            this.svcLvlField = value;
         }
      }

      /// <remarks/>
      public LocalInstrument2Choice LclInstrm
      {
         get
         {
            return this.lclInstrmField;
         }
         set
         {
            this.lclInstrmField = value;
         }
      }

      /// <remarks/>
      public CategoryPurpose1Choice CtgyPurp
      {
         get
         {
            return this.ctgyPurpField;
         }
         set
         {
            this.ctgyPurpField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class ServiceLevel8Choice
   {

      private string cdField;

      /// <remarks/>
      public string Cd
      {
         get
         {
            return this.cdField;
         }
         set
         {
            this.cdField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class LocalInstrument2Choice
   {

      private string itemField;

      private ItemChoiceType3 itemElementNameField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
      [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
      [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
      public string Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public ItemChoiceType3 ItemElementName
      {
         get
         {
            return this.itemElementNameField;
         }
         set
         {
            this.itemElementNameField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09", IncludeInSchema = false)]
   public enum ItemChoiceType3
   {

      /// <remarks/>
      Cd,

      /// <remarks/>
      Prtry,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class CategoryPurpose1Choice
   {

      private string itemField;

      private ItemChoiceType4 itemElementNameField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
      [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
      [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
      public string Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public ItemChoiceType4 ItemElementName
      {
         get
         {
            return this.itemElementNameField;
         }
         set
         {
            this.itemElementNameField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09", IncludeInSchema = false)]
   public enum ItemChoiceType4
   {

      /// <remarks/>
      Cd,

      /// <remarks/>
      Prtry,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class PaymentIdentification6
   {

      private string instrIdField;

      private string endToEndIdField;

      /// <remarks/>
      public string InstrId
      {
         get
         {
            return this.instrIdField;
         }
         set
         {
            this.instrIdField = value;
         }
      }

      /// <remarks/>
      public string EndToEndId
      {
         get
         {
            return this.endToEndIdField;
         }
         set
         {
            this.endToEndIdField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class CreditTransferTransaction34
   {

      private PaymentIdentification6 pmtIdField;

      private PaymentTypeInformation26CdtTrfTxInf pmtTpInfField;

      private AmountType4Choice amtField;

      private ChargeBearerType1Code chrgBrField;

      private bool chrgBrFieldSpecified;

      private PartyIdentification135_2 ultmtDbtrField;

      private BranchAndFinancialInstitutionIdentification6CdtrAgt cdtrAgtField;

      private PartyIdentification135_1 cdtrField;

      private CashAccount38Cdtr cdtrAcctField;

      private PartyIdentification135_2 ultmtCdtrField;

      private Purpose2Choice purpField;

      private RemittanceInformation16 rmtInfField;

      /// <remarks/>
      public PaymentIdentification6 PmtId
      {
         get
         {
            return this.pmtIdField;
         }
         set
         {
            this.pmtIdField = value;
         }
      }

      /// <remarks/>
      public PaymentTypeInformation26CdtTrfTxInf PmtTpInf
      {
         get
         {
            return this.pmtTpInfField;
         }
         set
         {
            this.pmtTpInfField = value;
         }
      }

      /// <remarks/>
      public AmountType4Choice Amt
      {
         get
         {
            return this.amtField;
         }
         set
         {
            this.amtField = value;
         }
      }

      /// <remarks/>
      public ChargeBearerType1Code ChrgBr
      {
         get
         {
            return this.chrgBrField;
         }
         set
         {
            this.chrgBrField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool ChrgBrSpecified
      {
         get
         {
            return this.chrgBrFieldSpecified;
         }
         set
         {
            this.chrgBrFieldSpecified = value;
         }
      }

      /// <remarks/>
      public PartyIdentification135_2 UltmtDbtr
      {
         get
         {
            return this.ultmtDbtrField;
         }
         set
         {
            this.ultmtDbtrField = value;
         }
      }

      /// <remarks/>
      public BranchAndFinancialInstitutionIdentification6CdtrAgt CdtrAgt
      {
         get
         {
            return this.cdtrAgtField;
         }
         set
         {
            this.cdtrAgtField = value;
         }
      }

      /// <remarks/>
      public PartyIdentification135_1 Cdtr
      {
         get
         {
            return this.cdtrField;
         }
         set
         {
            this.cdtrField = value;
         }
      }

      /// <remarks/>
      public CashAccount38Cdtr CdtrAcct
      {
         get
         {
            return this.cdtrAcctField;
         }
         set
         {
            this.cdtrAcctField = value;
         }
      }

      /// <remarks/>
      public PartyIdentification135_2 UltmtCdtr
      {
         get
         {
            return this.ultmtCdtrField;
         }
         set
         {
            this.ultmtCdtrField = value;
         }
      }

      /// <remarks/>
      public Purpose2Choice Purp
      {
         get
         {
            return this.purpField;
         }
         set
         {
            this.purpField = value;
         }
      }

      /// <remarks/>
      public RemittanceInformation16 RmtInf
      {
         get
         {
            return this.rmtInfField;
         }
         set
         {
            this.rmtInfField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public enum ChargeBearerType1Code
   {

      /// <remarks/>
      DEBT,

      /// <remarks/>
      CRED,

      /// <remarks/>
      SHAR,

      /// <remarks/>
      SLEV,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class PartyIdentification135_1
   {

      private string nmField;

      private PostalAddress24 pstlAdrField;

      private Party38Choice idField;

      /// <remarks/>
      public string Nm
      {
         get
         {
            return this.nmField;
         }
         set
         {
            this.nmField = value;
         }
      }

      /// <remarks/>
      public PostalAddress24 PstlAdr
      {
         get
         {
            return this.pstlAdrField;
         }
         set
         {
            this.pstlAdrField = value;
         }
      }

      [System.Xml.Serialization.XmlIgnoreAttribute()] // byQ 
      public bool IdSpecified { get; set; }

      /// <remarks/>
      public Party38Choice Id
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class GenericFinancialIdentification1
   {

      private Max35Text_NP idField;

      /// <remarks/>
      public Max35Text_NP Id
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public enum Max35Text_NP
   {

      /// <remarks/>
      NOTPROVIDED,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class FinancialInstitutionIdentification18DbtrAgt
   {

      private object itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("BICFI", typeof(string))]
      [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericFinancialIdentification1))]
      public object Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class BranchAndFinancialInstitutionIdentification6DbtrAgt
   {

      private FinancialInstitutionIdentification18DbtrAgt finInstnIdField;

      /// <remarks/>
      public FinancialInstitutionIdentification18DbtrAgt FinInstnId
      {
         get
         {
            return this.finInstnIdField;
         }
         set
         {
            this.finInstnIdField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class AccountIdentification4Choice
   {

      private string iBANField;

      /// <remarks/>
      public string IBAN
      {
         get
         {
            return this.iBANField;
         }
         set
         {
            this.iBANField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class CashAccount38Dbtr
   {

      private AccountIdentification4Choice idField;

      private string ccyField;

      /// <remarks/>
      public AccountIdentification4Choice Id
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }

      /// <remarks/>
      public string Ccy
      {
         get
         {
            return this.ccyField;
         }
         set
         {
            this.ccyField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class DateAndDateTime2Choice
   {

      private System.DateTime dtField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime Dt
      {
         get
         {
            return this.dtField;
         }
         set
         {
            this.dtField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class PaymentTypeInformation26PmtInf
   {

      private Priority2Code instrPrtyField;

      private bool instrPrtyFieldSpecified;

      private ServiceLevel8Choice svcLvlField;

      private LocalInstrument2Choice lclInstrmField;

      private CategoryPurpose1Choice ctgyPurpField;

      /// <remarks/>
      public Priority2Code InstrPrty
      {
         get
         {
            return this.instrPrtyField;
         }
         set
         {
            this.instrPrtyField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool InstrPrtySpecified
      {
         get
         {
            return this.instrPrtyFieldSpecified;
         }
         set
         {
            this.instrPrtyFieldSpecified = value;
         }
      }

      /// <remarks/>
      public ServiceLevel8Choice SvcLvl
      {
         get
         {
            return this.svcLvlField;
         }
         set
         {
            this.svcLvlField = value;
         }
      }

      /// <remarks/>
      public LocalInstrument2Choice LclInstrm
      {
         get
         {
            return this.lclInstrmField;
         }
         set
         {
            this.lclInstrmField = value;
         }
      }

      /// <remarks/>
      public CategoryPurpose1Choice CtgyPurp
      {
         get
         {
            return this.ctgyPurpField;
         }
         set
         {
            this.ctgyPurpField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public enum Priority2Code
   {

      /// <remarks/>
      HIGH,

      /// <remarks/>
      NORM,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class PaymentInstruction30
   {

      private string pmtInfIdField;

      private PaymentMethod3Code pmtMtdField;

      private bool btchBookgField;

      private bool btchBookgFieldSpecified;

      private string nbOfTxsField;

      private decimal ctrlSumField;

      private PaymentTypeInformation26PmtInf pmtTpInfField;

      private DateAndDateTime2Choice reqdExctnDtField;

      private PartyIdentification135_1 dbtrField;

      private CashAccount38Dbtr dbtrAcctField;

      private BranchAndFinancialInstitutionIdentification6DbtrAgt dbtrAgtField;

      private PartyIdentification135_2 ultmtDbtrField;

      private ChargeBearerType1Code chrgBrField;

      private bool chrgBrFieldSpecified;

      private CreditTransferTransaction34[] cdtTrfTxInfField;

      /// <remarks/>
      public string PmtInfId
      {
         get
         {
            return this.pmtInfIdField;
         }
         set
         {
            this.pmtInfIdField = value;
         }
      }

      /// <remarks/>
      public PaymentMethod3Code PmtMtd
      {
         get
         {
            return this.pmtMtdField;
         }
         set
         {
            this.pmtMtdField = value;
         }
      }

      /// <remarks/>
      public bool BtchBookg
      {
         get
         {
            return this.btchBookgField;
         }
         set
         {
            this.btchBookgField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool BtchBookgSpecified
      {
         get
         {
            return this.btchBookgFieldSpecified;
         }
         set
         {
            this.btchBookgFieldSpecified = value;
         }
      }

      /// <remarks/>
      public string NbOfTxs
      {
         get
         {
            return this.nbOfTxsField;
         }
         set
         {
            this.nbOfTxsField = value;
         }
      }

      /// <remarks/>
      public decimal CtrlSum
      {
         get
         {
            return this.ctrlSumField;
         }
         set
         {
            this.ctrlSumField = value;
         }
      }

      /// <remarks/>
      public PaymentTypeInformation26PmtInf PmtTpInf
      {
         get
         {
            return this.pmtTpInfField;
         }
         set
         {
            this.pmtTpInfField = value;
         }
      }

      /// <remarks/>
      public DateAndDateTime2Choice ReqdExctnDt
      {
         get
         {
            return this.reqdExctnDtField;
         }
         set
         {
            this.reqdExctnDtField = value;
         }
      }

      /// <remarks/>
      public PartyIdentification135_1 Dbtr
      {
         get
         {
            return this.dbtrField;
         }
         set
         {
            this.dbtrField = value;
         }
      }

      /// <remarks/>
      public CashAccount38Dbtr DbtrAcct
      {
         get
         {
            return this.dbtrAcctField;
         }
         set
         {
            this.dbtrAcctField = value;
         }
      }

      /// <remarks/>
      public BranchAndFinancialInstitutionIdentification6DbtrAgt DbtrAgt
      {
         get
         {
            return this.dbtrAgtField;
         }
         set
         {
            this.dbtrAgtField = value;
         }
      }

      /// <remarks/>
      public PartyIdentification135_2 UltmtDbtr
      {
         get
         {
            return this.ultmtDbtrField;
         }
         set
         {
            this.ultmtDbtrField = value;
         }
      }

      /// <remarks/>
      public ChargeBearerType1Code ChrgBr
      {
         get
         {
            return this.chrgBrField;
         }
         set
         {
            this.chrgBrField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool ChrgBrSpecified
      {
         get
         {
            return this.chrgBrFieldSpecified;
         }
         set
         {
            this.chrgBrFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("CdtTrfTxInf")]
      public CreditTransferTransaction34[] CdtTrfTxInf
      {
         get
         {
            return this.cdtTrfTxInfField;
         }
         set
         {
            this.cdtTrfTxInfField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public enum PaymentMethod3Code
   {

      /// <remarks/>
      TRF,

      /// <remarks/>
      CHK,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class PersonIdentificationSchemeName1Choice
   {

      private string itemField;

      private ItemChoiceType2 itemElementNameField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
      [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
      [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
      public string Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public ItemChoiceType2 ItemElementName
      {
         get
         {
            return this.itemElementNameField;
         }
         set
         {
            this.itemElementNameField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09", IncludeInSchema = false)]
   public enum ItemChoiceType2
   {

      /// <remarks/>
      Cd,

      /// <remarks/>
      Prtry,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class GenericPersonIdentification1
   {

      private string idField;

      private PersonIdentificationSchemeName1Choice schmeNmField;

      private string issrField;

      /// <remarks/>
      public string Id
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }

      /// <remarks/>
      public PersonIdentificationSchemeName1Choice SchmeNm
      {
         get
         {
            return this.schmeNmField;
         }
         set
         {
            this.schmeNmField = value;
         }
      }

      /// <remarks/>
      public string Issr
      {
         get
         {
            return this.issrField;
         }
         set
         {
            this.issrField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class DateAndPlaceOfBirth1
   {

      private System.DateTime birthDtField;

      private string prvcOfBirthField;

      private string cityOfBirthField;

      private string ctryOfBirthField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime BirthDt
      {
         get
         {
            return this.birthDtField;
         }
         set
         {
            this.birthDtField = value;
         }
      }

      /// <remarks/>
      public string PrvcOfBirth
      {
         get
         {
            return this.prvcOfBirthField;
         }
         set
         {
            this.prvcOfBirthField = value;
         }
      }

      /// <remarks/>
      public string CityOfBirth
      {
         get
         {
            return this.cityOfBirthField;
         }
         set
         {
            this.cityOfBirthField = value;
         }
      }

      /// <remarks/>
      public string CtryOfBirth
      {
         get
         {
            return this.ctryOfBirthField;
         }
         set
         {
            this.ctryOfBirthField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09")]
   public partial class PersonIdentification13
   {

      private object itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("DtAndPlcOfBirth", typeof(DateAndPlaceOfBirth1))]
      [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericPersonIdentification1))]
      public object Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09", IncludeInSchema = false)]
   public enum ItemChoiceType1
   {

      /// <remarks/>
      AnyBIC,

      /// <remarks/>
      LEI,

      /// <remarks/>
      Othr,
   }
}