//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Vektor.DataLayer.DS_FindRecord {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DS_findMixer")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_findMixer : global::System.Data.DataSet {
        
        private mixerDataTable tablemixer;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public DS_findMixer() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected DS_findMixer(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["mixer"] != null)) {
                    base.Tables.Add(new mixerDataTable(ds.Tables["mixer"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public mixerDataTable mixer {
            get {
                return this.tablemixer;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DS_findMixer cln = ((DS_findMixer)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["mixer"] != null)) {
                    base.Tables.Add(new mixerDataTable(ds.Tables["mixer"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tablemixer = ((mixerDataTable)(base.Tables["mixer"]));
            if ((initTable == true)) {
                if ((this.tablemixer != null)) {
                    this.tablemixer.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DS_findMixer";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_findMixer.xsd";
            this.EnforceConstraints = false;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablemixer = new mixerDataTable();
            base.Tables.Add(this.tablemixer);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializemixer() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DS_findMixer ds = new DS_findMixer();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void mixerRowChangeEventHandler(object sender, mixerRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class mixerDataTable : global::System.Data.TypedTableBase<mixerRow> {
            
            private global::System.Data.DataColumn columnrecID;
            
            private global::System.Data.DataColumn columnaddTS;
            
            private global::System.Data.DataColumn columnmodTS;
            
            private global::System.Data.DataColumn columnaddUID;
            
            private global::System.Data.DataColumn columnmodUID;
            
            private global::System.Data.DataColumn columndokNum;
            
            private global::System.Data.DataColumn columndokDate;
            
            private global::System.Data.DataColumn columntt;
            
            private global::System.Data.DataColumn columnttNum;
            
            private global::System.Data.DataColumn columnnapomena;
            
            private global::System.Data.DataColumn columnintA;
            
            private global::System.Data.DataColumn columndateA;
            
            private global::System.Data.DataColumn columnkupdobCD;
            
            private global::System.Data.DataColumn columnmtrosCD;
            
            private global::System.Data.DataColumn columnpersonCD;
            
            private global::System.Data.DataColumn columnintB;
            
            private global::System.Data.DataColumn columnisXxx;
            
            private global::System.Data.DataColumn columnkonto;
            
            private global::System.Data.DataColumn columnkupdobTK;
            
            private global::System.Data.DataColumn columnkupdobName;
            
            private global::System.Data.DataColumn columnmtrosTK;
            
            private global::System.Data.DataColumn columnpersonIme;
            
            private global::System.Data.DataColumn columnpersonPrezim;
            
            private global::System.Data.DataColumn columndevName;
            
            private global::System.Data.DataColumn columnstrA_40;
            
            private global::System.Data.DataColumn columnstrB_128;
            
            private global::System.Data.DataColumn columnstrC_32;
            
            private global::System.Data.DataColumn columnstrD_32;
            
            private global::System.Data.DataColumn columnstrE_256;
            
            private global::System.Data.DataColumn columnstrF_64;
            
            private global::System.Data.DataColumn columnstrG_40;
            
            private global::System.Data.DataColumn columndateTimeA;
            
            private global::System.Data.DataColumn columndateTimeB;
            
            private global::System.Data.DataColumn columndateB;
            
            private global::System.Data.DataColumn columnmoneyA;
            
            private global::System.Data.DataColumn columnmoneyB;
            
            private global::System.Data.DataColumn columnmoneyC;
            
            private global::System.Data.DataColumn columnstrH_32;
            
            private global::System.Data.DataColumn columnprojektCD;
            
            private global::System.Data.DataColumn columnorigRecID;
            
            private global::System.Data.DataColumn columnrecVer;
            
            private global::System.Data.DataColumn columnarAction;
            
            private global::System.Data.DataColumn columnarTS;
            
            private global::System.Data.DataColumn columnarUID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public mixerDataTable() {
                this.TableName = "mixer";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal mixerDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected mixerDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn recIDColumn {
                get {
                    return this.columnrecID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn addTSColumn {
                get {
                    return this.columnaddTS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn modTSColumn {
                get {
                    return this.columnmodTS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn addUIDColumn {
                get {
                    return this.columnaddUID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn modUIDColumn {
                get {
                    return this.columnmodUID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn dokNumColumn {
                get {
                    return this.columndokNum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn dokDateColumn {
                get {
                    return this.columndokDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ttColumn {
                get {
                    return this.columntt;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ttNumColumn {
                get {
                    return this.columnttNum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn napomenaColumn {
                get {
                    return this.columnnapomena;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn intAColumn {
                get {
                    return this.columnintA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn dateAColumn {
                get {
                    return this.columndateA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn kupdobCDColumn {
                get {
                    return this.columnkupdobCD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn mtrosCDColumn {
                get {
                    return this.columnmtrosCD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn personCDColumn {
                get {
                    return this.columnpersonCD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn intBColumn {
                get {
                    return this.columnintB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn isXxxColumn {
                get {
                    return this.columnisXxx;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn kontoColumn {
                get {
                    return this.columnkonto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn kupdobTKColumn {
                get {
                    return this.columnkupdobTK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn kupdobNameColumn {
                get {
                    return this.columnkupdobName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn mtrosTKColumn {
                get {
                    return this.columnmtrosTK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn personImeColumn {
                get {
                    return this.columnpersonIme;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn personPrezimColumn {
                get {
                    return this.columnpersonPrezim;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn devNameColumn {
                get {
                    return this.columndevName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn strA_40Column {
                get {
                    return this.columnstrA_40;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn strB_128Column {
                get {
                    return this.columnstrB_128;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn strC_32Column {
                get {
                    return this.columnstrC_32;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn strD_32Column {
                get {
                    return this.columnstrD_32;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn strE_256Column {
                get {
                    return this.columnstrE_256;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn strF_64Column {
                get {
                    return this.columnstrF_64;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn strG_40Column {
                get {
                    return this.columnstrG_40;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn dateTimeAColumn {
                get {
                    return this.columndateTimeA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn dateTimeBColumn {
                get {
                    return this.columndateTimeB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn dateBColumn {
                get {
                    return this.columndateB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn moneyAColumn {
                get {
                    return this.columnmoneyA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn moneyBColumn {
                get {
                    return this.columnmoneyB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn moneyCColumn {
                get {
                    return this.columnmoneyC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn strH_32Column {
                get {
                    return this.columnstrH_32;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn projektCDColumn {
                get {
                    return this.columnprojektCD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn origRecIDColumn {
                get {
                    return this.columnorigRecID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn recVerColumn {
                get {
                    return this.columnrecVer;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn arActionColumn {
                get {
                    return this.columnarAction;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn arTSColumn {
                get {
                    return this.columnarTS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn arUIDColumn {
                get {
                    return this.columnarUID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public mixerRow this[int index] {
                get {
                    return ((mixerRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event mixerRowChangeEventHandler mixerRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event mixerRowChangeEventHandler mixerRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event mixerRowChangeEventHandler mixerRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event mixerRowChangeEventHandler mixerRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddmixerRow(mixerRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public mixerRow AddmixerRow(
                        uint recID, 
                        System.DateTime addTS, 
                        System.DateTime modTS, 
                        string addUID, 
                        string modUID, 
                        uint dokNum, 
                        System.DateTime dokDate, 
                        string tt, 
                        uint ttNum, 
                        string napomena, 
                        uint intA, 
                        System.DateTime dateA, 
                        uint kupdobCD, 
                        uint mtrosCD, 
                        uint personCD, 
                        int intB, 
                        byte isXxx, 
                        string konto, 
                        string kupdobTK, 
                        string kupdobName, 
                        string mtrosTK, 
                        string personIme, 
                        string personPrezim, 
                        string devName, 
                        string strA_40, 
                        string strB_128, 
                        string strC_32, 
                        string strD_32, 
                        string strE_256, 
                        string strF_64, 
                        string strG_40, 
                        System.DateTime dateTimeA, 
                        System.DateTime dateTimeB, 
                        System.DateTime dateB, 
                        decimal moneyA, 
                        decimal moneyB, 
                        decimal moneyC, 
                        string strH_32, 
                        string projektCD, 
                        uint origRecID, 
                        ushort recVer, 
                        string arAction, 
                        System.DateTime arTS, 
                        string arUID) {
                mixerRow rowmixerRow = ((mixerRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        recID,
                        addTS,
                        modTS,
                        addUID,
                        modUID,
                        dokNum,
                        dokDate,
                        tt,
                        ttNum,
                        napomena,
                        intA,
                        dateA,
                        kupdobCD,
                        mtrosCD,
                        personCD,
                        intB,
                        isXxx,
                        konto,
                        kupdobTK,
                        kupdobName,
                        mtrosTK,
                        personIme,
                        personPrezim,
                        devName,
                        strA_40,
                        strB_128,
                        strC_32,
                        strD_32,
                        strE_256,
                        strF_64,
                        strG_40,
                        dateTimeA,
                        dateTimeB,
                        dateB,
                        moneyA,
                        moneyB,
                        moneyC,
                        strH_32,
                        projektCD,
                        origRecID,
                        recVer,
                        arAction,
                        arTS,
                        arUID};
                rowmixerRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowmixerRow);
                return rowmixerRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                mixerDataTable cln = ((mixerDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new mixerDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnrecID = base.Columns["recID"];
                this.columnaddTS = base.Columns["addTS"];
                this.columnmodTS = base.Columns["modTS"];
                this.columnaddUID = base.Columns["addUID"];
                this.columnmodUID = base.Columns["modUID"];
                this.columndokNum = base.Columns["dokNum"];
                this.columndokDate = base.Columns["dokDate"];
                this.columntt = base.Columns["tt"];
                this.columnttNum = base.Columns["ttNum"];
                this.columnnapomena = base.Columns["napomena"];
                this.columnintA = base.Columns["intA"];
                this.columndateA = base.Columns["dateA"];
                this.columnkupdobCD = base.Columns["kupdobCD"];
                this.columnmtrosCD = base.Columns["mtrosCD"];
                this.columnpersonCD = base.Columns["personCD"];
                this.columnintB = base.Columns["intB"];
                this.columnisXxx = base.Columns["isXxx"];
                this.columnkonto = base.Columns["konto"];
                this.columnkupdobTK = base.Columns["kupdobTK"];
                this.columnkupdobName = base.Columns["kupdobName"];
                this.columnmtrosTK = base.Columns["mtrosTK"];
                this.columnpersonIme = base.Columns["personIme"];
                this.columnpersonPrezim = base.Columns["personPrezim"];
                this.columndevName = base.Columns["devName"];
                this.columnstrA_40 = base.Columns["strA_40"];
                this.columnstrB_128 = base.Columns["strB_128"];
                this.columnstrC_32 = base.Columns["strC_32"];
                this.columnstrD_32 = base.Columns["strD_32"];
                this.columnstrE_256 = base.Columns["strE_256"];
                this.columnstrF_64 = base.Columns["strF_64"];
                this.columnstrG_40 = base.Columns["strG_40"];
                this.columndateTimeA = base.Columns["dateTimeA"];
                this.columndateTimeB = base.Columns["dateTimeB"];
                this.columndateB = base.Columns["dateB"];
                this.columnmoneyA = base.Columns["moneyA"];
                this.columnmoneyB = base.Columns["moneyB"];
                this.columnmoneyC = base.Columns["moneyC"];
                this.columnstrH_32 = base.Columns["strH_32"];
                this.columnprojektCD = base.Columns["projektCD"];
                this.columnorigRecID = base.Columns["origRecID"];
                this.columnrecVer = base.Columns["recVer"];
                this.columnarAction = base.Columns["arAction"];
                this.columnarTS = base.Columns["arTS"];
                this.columnarUID = base.Columns["arUID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnrecID = new global::System.Data.DataColumn("recID", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrecID);
                this.columnaddTS = new global::System.Data.DataColumn("addTS", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnaddTS);
                this.columnmodTS = new global::System.Data.DataColumn("modTS", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmodTS);
                this.columnaddUID = new global::System.Data.DataColumn("addUID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnaddUID);
                this.columnmodUID = new global::System.Data.DataColumn("modUID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmodUID);
                this.columndokNum = new global::System.Data.DataColumn("dokNum", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndokNum);
                this.columndokDate = new global::System.Data.DataColumn("dokDate", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndokDate);
                this.columntt = new global::System.Data.DataColumn("tt", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntt);
                this.columnttNum = new global::System.Data.DataColumn("ttNum", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttNum);
                this.columnnapomena = new global::System.Data.DataColumn("napomena", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnapomena);
                this.columnintA = new global::System.Data.DataColumn("intA", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnintA);
                this.columndateA = new global::System.Data.DataColumn("dateA", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndateA);
                this.columnkupdobCD = new global::System.Data.DataColumn("kupdobCD", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkupdobCD);
                this.columnmtrosCD = new global::System.Data.DataColumn("mtrosCD", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmtrosCD);
                this.columnpersonCD = new global::System.Data.DataColumn("personCD", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpersonCD);
                this.columnintB = new global::System.Data.DataColumn("intB", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnintB);
                this.columnisXxx = new global::System.Data.DataColumn("isXxx", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnisXxx);
                this.columnkonto = new global::System.Data.DataColumn("konto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkonto);
                this.columnkupdobTK = new global::System.Data.DataColumn("kupdobTK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkupdobTK);
                this.columnkupdobName = new global::System.Data.DataColumn("kupdobName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkupdobName);
                this.columnmtrosTK = new global::System.Data.DataColumn("mtrosTK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmtrosTK);
                this.columnpersonIme = new global::System.Data.DataColumn("personIme", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpersonIme);
                this.columnpersonPrezim = new global::System.Data.DataColumn("personPrezim", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpersonPrezim);
                this.columndevName = new global::System.Data.DataColumn("devName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndevName);
                this.columnstrA_40 = new global::System.Data.DataColumn("strA_40", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrA_40);
                this.columnstrB_128 = new global::System.Data.DataColumn("strB_128", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrB_128);
                this.columnstrC_32 = new global::System.Data.DataColumn("strC_32", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrC_32);
                this.columnstrD_32 = new global::System.Data.DataColumn("strD_32", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrD_32);
                this.columnstrE_256 = new global::System.Data.DataColumn("strE_256", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrE_256);
                this.columnstrF_64 = new global::System.Data.DataColumn("strF_64", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrF_64);
                this.columnstrG_40 = new global::System.Data.DataColumn("strG_40", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrG_40);
                this.columndateTimeA = new global::System.Data.DataColumn("dateTimeA", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndateTimeA);
                this.columndateTimeB = new global::System.Data.DataColumn("dateTimeB", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndateTimeB);
                this.columndateB = new global::System.Data.DataColumn("dateB", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndateB);
                this.columnmoneyA = new global::System.Data.DataColumn("moneyA", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmoneyA);
                this.columnmoneyB = new global::System.Data.DataColumn("moneyB", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmoneyB);
                this.columnmoneyC = new global::System.Data.DataColumn("moneyC", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmoneyC);
                this.columnstrH_32 = new global::System.Data.DataColumn("strH_32", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrH_32);
                this.columnprojektCD = new global::System.Data.DataColumn("projektCD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnprojektCD);
                this.columnorigRecID = new global::System.Data.DataColumn("origRecID", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnorigRecID);
                this.columnrecVer = new global::System.Data.DataColumn("recVer", typeof(ushort), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrecVer);
                this.columnarAction = new global::System.Data.DataColumn("arAction", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnarAction);
                this.columnarTS = new global::System.Data.DataColumn("arTS", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnarTS);
                this.columnarUID = new global::System.Data.DataColumn("arUID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnarUID);
                this.columnrecID.AllowDBNull = false;
                this.columnaddTS.AllowDBNull = false;
                this.columnmodTS.AllowDBNull = false;
                this.columnaddUID.AllowDBNull = false;
                this.columnaddUID.MaxLength = 16;
                this.columnmodUID.AllowDBNull = false;
                this.columnmodUID.MaxLength = 16;
                this.columndokNum.AllowDBNull = false;
                this.columndokDate.AllowDBNull = false;
                this.columntt.AllowDBNull = false;
                this.columntt.MaxLength = 3;
                this.columnttNum.AllowDBNull = false;
                this.columnnapomena.AllowDBNull = false;
                this.columnnapomena.MaxLength = 80;
                this.columnintA.AllowDBNull = false;
                this.columndateA.AllowDBNull = false;
                this.columnkupdobCD.AllowDBNull = false;
                this.columnmtrosCD.AllowDBNull = false;
                this.columnpersonCD.AllowDBNull = false;
                this.columnintB.AllowDBNull = false;
                this.columnisXxx.AllowDBNull = false;
                this.columnkonto.AllowDBNull = false;
                this.columnkonto.MaxLength = 8;
                this.columnkupdobTK.AllowDBNull = false;
                this.columnkupdobTK.MaxLength = 6;
                this.columnkupdobName.AllowDBNull = false;
                this.columnkupdobName.MaxLength = 50;
                this.columnmtrosTK.AllowDBNull = false;
                this.columnmtrosTK.MaxLength = 6;
                this.columnpersonIme.AllowDBNull = false;
                this.columnpersonIme.MaxLength = 24;
                this.columnpersonPrezim.AllowDBNull = false;
                this.columnpersonPrezim.MaxLength = 32;
                this.columndevName.AllowDBNull = false;
                this.columndevName.MaxLength = 3;
                this.columnstrA_40.AllowDBNull = false;
                this.columnstrA_40.MaxLength = 40;
                this.columnstrB_128.AllowDBNull = false;
                this.columnstrB_128.MaxLength = 128;
                this.columnstrC_32.AllowDBNull = false;
                this.columnstrC_32.MaxLength = 32;
                this.columnstrD_32.AllowDBNull = false;
                this.columnstrD_32.MaxLength = 32;
                this.columnstrE_256.AllowDBNull = false;
                this.columnstrE_256.MaxLength = 256;
                this.columnstrF_64.AllowDBNull = false;
                this.columnstrF_64.MaxLength = 64;
                this.columnstrG_40.AllowDBNull = false;
                this.columnstrG_40.MaxLength = 40;
                this.columndateTimeA.AllowDBNull = false;
                this.columndateTimeB.AllowDBNull = false;
                this.columndateB.AllowDBNull = false;
                this.columnmoneyA.AllowDBNull = false;
                this.columnmoneyB.AllowDBNull = false;
                this.columnmoneyC.AllowDBNull = false;
                this.columnstrH_32.AllowDBNull = false;
                this.columnstrH_32.MaxLength = 32;
                this.columnprojektCD.AllowDBNull = false;
                this.columnprojektCD.MaxLength = 16;
                this.columnorigRecID.AllowDBNull = false;
                this.columnrecVer.AllowDBNull = false;
                this.columnarAction.AllowDBNull = false;
                this.columnarAction.MaxLength = 8;
                this.columnarTS.AllowDBNull = false;
                this.columnarUID.AllowDBNull = false;
                this.columnarUID.MaxLength = 16;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public mixerRow NewmixerRow() {
                return ((mixerRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new mixerRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(mixerRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.mixerRowChanged != null)) {
                    this.mixerRowChanged(this, new mixerRowChangeEvent(((mixerRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.mixerRowChanging != null)) {
                    this.mixerRowChanging(this, new mixerRowChangeEvent(((mixerRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.mixerRowDeleted != null)) {
                    this.mixerRowDeleted(this, new mixerRowChangeEvent(((mixerRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.mixerRowDeleting != null)) {
                    this.mixerRowDeleting(this, new mixerRowChangeEvent(((mixerRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemovemixerRow(mixerRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DS_findMixer ds = new DS_findMixer();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "mixerDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class mixerRow : global::System.Data.DataRow {
            
            private mixerDataTable tablemixer;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal mixerRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablemixer = ((mixerDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint recID {
                get {
                    return ((uint)(this[this.tablemixer.recIDColumn]));
                }
                set {
                    this[this.tablemixer.recIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime addTS {
                get {
                    return ((global::System.DateTime)(this[this.tablemixer.addTSColumn]));
                }
                set {
                    this[this.tablemixer.addTSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime modTS {
                get {
                    return ((global::System.DateTime)(this[this.tablemixer.modTSColumn]));
                }
                set {
                    this[this.tablemixer.modTSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string addUID {
                get {
                    return ((string)(this[this.tablemixer.addUIDColumn]));
                }
                set {
                    this[this.tablemixer.addUIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string modUID {
                get {
                    return ((string)(this[this.tablemixer.modUIDColumn]));
                }
                set {
                    this[this.tablemixer.modUIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint dokNum {
                get {
                    return ((uint)(this[this.tablemixer.dokNumColumn]));
                }
                set {
                    this[this.tablemixer.dokNumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime dokDate {
                get {
                    return ((global::System.DateTime)(this[this.tablemixer.dokDateColumn]));
                }
                set {
                    this[this.tablemixer.dokDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string tt {
                get {
                    return ((string)(this[this.tablemixer.ttColumn]));
                }
                set {
                    this[this.tablemixer.ttColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint ttNum {
                get {
                    return ((uint)(this[this.tablemixer.ttNumColumn]));
                }
                set {
                    this[this.tablemixer.ttNumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string napomena {
                get {
                    return ((string)(this[this.tablemixer.napomenaColumn]));
                }
                set {
                    this[this.tablemixer.napomenaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint intA {
                get {
                    return ((uint)(this[this.tablemixer.intAColumn]));
                }
                set {
                    this[this.tablemixer.intAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime dateA {
                get {
                    return ((global::System.DateTime)(this[this.tablemixer.dateAColumn]));
                }
                set {
                    this[this.tablemixer.dateAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint kupdobCD {
                get {
                    return ((uint)(this[this.tablemixer.kupdobCDColumn]));
                }
                set {
                    this[this.tablemixer.kupdobCDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint mtrosCD {
                get {
                    return ((uint)(this[this.tablemixer.mtrosCDColumn]));
                }
                set {
                    this[this.tablemixer.mtrosCDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint personCD {
                get {
                    return ((uint)(this[this.tablemixer.personCDColumn]));
                }
                set {
                    this[this.tablemixer.personCDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int intB {
                get {
                    return ((int)(this[this.tablemixer.intBColumn]));
                }
                set {
                    this[this.tablemixer.intBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public byte isXxx {
                get {
                    return ((byte)(this[this.tablemixer.isXxxColumn]));
                }
                set {
                    this[this.tablemixer.isXxxColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string konto {
                get {
                    return ((string)(this[this.tablemixer.kontoColumn]));
                }
                set {
                    this[this.tablemixer.kontoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string kupdobTK {
                get {
                    return ((string)(this[this.tablemixer.kupdobTKColumn]));
                }
                set {
                    this[this.tablemixer.kupdobTKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string kupdobName {
                get {
                    return ((string)(this[this.tablemixer.kupdobNameColumn]));
                }
                set {
                    this[this.tablemixer.kupdobNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string mtrosTK {
                get {
                    return ((string)(this[this.tablemixer.mtrosTKColumn]));
                }
                set {
                    this[this.tablemixer.mtrosTKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string personIme {
                get {
                    return ((string)(this[this.tablemixer.personImeColumn]));
                }
                set {
                    this[this.tablemixer.personImeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string personPrezim {
                get {
                    return ((string)(this[this.tablemixer.personPrezimColumn]));
                }
                set {
                    this[this.tablemixer.personPrezimColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string devName {
                get {
                    return ((string)(this[this.tablemixer.devNameColumn]));
                }
                set {
                    this[this.tablemixer.devNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string strA_40 {
                get {
                    return ((string)(this[this.tablemixer.strA_40Column]));
                }
                set {
                    this[this.tablemixer.strA_40Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string strB_128 {
                get {
                    return ((string)(this[this.tablemixer.strB_128Column]));
                }
                set {
                    this[this.tablemixer.strB_128Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string strC_32 {
                get {
                    return ((string)(this[this.tablemixer.strC_32Column]));
                }
                set {
                    this[this.tablemixer.strC_32Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string strD_32 {
                get {
                    return ((string)(this[this.tablemixer.strD_32Column]));
                }
                set {
                    this[this.tablemixer.strD_32Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string strE_256 {
                get {
                    return ((string)(this[this.tablemixer.strE_256Column]));
                }
                set {
                    this[this.tablemixer.strE_256Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string strF_64 {
                get {
                    return ((string)(this[this.tablemixer.strF_64Column]));
                }
                set {
                    this[this.tablemixer.strF_64Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string strG_40 {
                get {
                    return ((string)(this[this.tablemixer.strG_40Column]));
                }
                set {
                    this[this.tablemixer.strG_40Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime dateTimeA {
                get {
                    return ((global::System.DateTime)(this[this.tablemixer.dateTimeAColumn]));
                }
                set {
                    this[this.tablemixer.dateTimeAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime dateTimeB {
                get {
                    return ((global::System.DateTime)(this[this.tablemixer.dateTimeBColumn]));
                }
                set {
                    this[this.tablemixer.dateTimeBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime dateB {
                get {
                    return ((global::System.DateTime)(this[this.tablemixer.dateBColumn]));
                }
                set {
                    this[this.tablemixer.dateBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public decimal moneyA {
                get {
                    return ((decimal)(this[this.tablemixer.moneyAColumn]));
                }
                set {
                    this[this.tablemixer.moneyAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public decimal moneyB {
                get {
                    return ((decimal)(this[this.tablemixer.moneyBColumn]));
                }
                set {
                    this[this.tablemixer.moneyBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public decimal moneyC {
                get {
                    return ((decimal)(this[this.tablemixer.moneyCColumn]));
                }
                set {
                    this[this.tablemixer.moneyCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string strH_32 {
                get {
                    return ((string)(this[this.tablemixer.strH_32Column]));
                }
                set {
                    this[this.tablemixer.strH_32Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string projektCD {
                get {
                    return ((string)(this[this.tablemixer.projektCDColumn]));
                }
                set {
                    this[this.tablemixer.projektCDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint origRecID {
                get {
                    return ((uint)(this[this.tablemixer.origRecIDColumn]));
                }
                set {
                    this[this.tablemixer.origRecIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public ushort recVer {
                get {
                    return ((ushort)(this[this.tablemixer.recVerColumn]));
                }
                set {
                    this[this.tablemixer.recVerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string arAction {
                get {
                    return ((string)(this[this.tablemixer.arActionColumn]));
                }
                set {
                    this[this.tablemixer.arActionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime arTS {
                get {
                    return ((global::System.DateTime)(this[this.tablemixer.arTSColumn]));
                }
                set {
                    this[this.tablemixer.arTSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string arUID {
                get {
                    return ((string)(this[this.tablemixer.arUIDColumn]));
                }
                set {
                    this[this.tablemixer.arUIDColumn] = value;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class mixerRowChangeEvent : global::System.EventArgs {
            
            private mixerRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public mixerRowChangeEvent(mixerRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public mixerRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591