//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Vektor.DataLayer.DS_FindRecord {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DS_findSkyRule")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_findSkyRule : global::System.Data.DataSet {
        
        private skyruleDataTable tableskyrule;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public DS_findSkyRule() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected DS_findSkyRule(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["skyrule"] != null)) {
                    base.Tables.Add(new skyruleDataTable(ds.Tables["skyrule"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public skyruleDataTable skyrule {
            get {
                return this.tableskyrule;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DS_findSkyRule cln = ((DS_findSkyRule)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["skyrule"] != null)) {
                    base.Tables.Add(new skyruleDataTable(ds.Tables["skyrule"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableskyrule = ((skyruleDataTable)(base.Tables["skyrule"]));
            if ((initTable == true)) {
                if ((this.tableskyrule != null)) {
                    this.tableskyrule.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DS_findSkyRule";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_findSkyRule.xsd";
            this.EnforceConstraints = false;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableskyrule = new skyruleDataTable();
            base.Tables.Add(this.tableskyrule);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializeskyrule() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DS_findSkyRule ds = new DS_findSkyRule();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void skyruleRowChangeEventHandler(object sender, skyruleRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class skyruleDataTable : global::System.Data.TypedTableBase<skyruleRow> {
            
            private global::System.Data.DataColumn columnrecID;
            
            private global::System.Data.DataColumn columnaddTS;
            
            private global::System.Data.DataColumn columnmodTS;
            
            private global::System.Data.DataColumn columnaddUID;
            
            private global::System.Data.DataColumn columnmodUID;
            
            private global::System.Data.DataColumn columnlanSrvID;
            
            private global::System.Data.DataColumn columnlanRecID;
            
            private global::System.Data.DataColumn columnorigRecID;
            
            private global::System.Data.DataColumn columnrecVer;
            
            private global::System.Data.DataColumn columnarAction;
            
            private global::System.Data.DataColumn columnarTS;
            
            private global::System.Data.DataColumn columnarUID;
            
            private global::System.Data.DataColumn columnrecord;
            
            private global::System.Data.DataColumn columndocumTT;
            
            private global::System.Data.DataColumn columnbirthLoc;
            
            private global::System.Data.DataColumn columnskl1kind;
            
            private global::System.Data.DataColumn columnskl2kind;
            
            private global::System.Data.DataColumn columncentOPS;
            
            private global::System.Data.DataColumn columnshopOPS;
            
            private global::System.Data.DataColumn columnshopRCVkind;
            
            private global::System.Data.DataColumn columncentCanADD;
            
            private global::System.Data.DataColumn columncentCanRWT;
            
            private global::System.Data.DataColumn columncentCanDEL;
            
            private global::System.Data.DataColumn columnshopCanADD;
            
            private global::System.Data.DataColumn columnshopCanRWT;
            
            private global::System.Data.DataColumn columnshopCanDEL;
            
            private global::System.Data.DataColumn columnopis;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public skyruleDataTable() {
                this.TableName = "skyrule";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal skyruleDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected skyruleDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn recIDColumn {
                get {
                    return this.columnrecID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn addTSColumn {
                get {
                    return this.columnaddTS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn modTSColumn {
                get {
                    return this.columnmodTS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn addUIDColumn {
                get {
                    return this.columnaddUID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn modUIDColumn {
                get {
                    return this.columnmodUID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn lanSrvIDColumn {
                get {
                    return this.columnlanSrvID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn lanRecIDColumn {
                get {
                    return this.columnlanRecID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn origRecIDColumn {
                get {
                    return this.columnorigRecID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn recVerColumn {
                get {
                    return this.columnrecVer;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn arActionColumn {
                get {
                    return this.columnarAction;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn arTSColumn {
                get {
                    return this.columnarTS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn arUIDColumn {
                get {
                    return this.columnarUID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn recordColumn {
                get {
                    return this.columnrecord;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn documTTColumn {
                get {
                    return this.columndocumTT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn birthLocColumn {
                get {
                    return this.columnbirthLoc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn skl1kindColumn {
                get {
                    return this.columnskl1kind;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn skl2kindColumn {
                get {
                    return this.columnskl2kind;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn centOPSColumn {
                get {
                    return this.columncentOPS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn shopOPSColumn {
                get {
                    return this.columnshopOPS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn shopRCVkindColumn {
                get {
                    return this.columnshopRCVkind;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn centCanADDColumn {
                get {
                    return this.columncentCanADD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn centCanRWTColumn {
                get {
                    return this.columncentCanRWT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn centCanDELColumn {
                get {
                    return this.columncentCanDEL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn shopCanADDColumn {
                get {
                    return this.columnshopCanADD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn shopCanRWTColumn {
                get {
                    return this.columnshopCanRWT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn shopCanDELColumn {
                get {
                    return this.columnshopCanDEL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn opisColumn {
                get {
                    return this.columnopis;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public skyruleRow this[int index] {
                get {
                    return ((skyruleRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event skyruleRowChangeEventHandler skyruleRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event skyruleRowChangeEventHandler skyruleRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event skyruleRowChangeEventHandler skyruleRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event skyruleRowChangeEventHandler skyruleRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddskyruleRow(skyruleRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public skyruleRow AddskyruleRow(
                        uint recID, 
                        System.DateTime addTS, 
                        System.DateTime modTS, 
                        string addUID, 
                        string modUID, 
                        uint lanSrvID, 
                        uint lanRecID, 
                        uint origRecID, 
                        ushort recVer, 
                        string arAction, 
                        System.DateTime arTS, 
                        string arUID, 
                        string record, 
                        string documTT, 
                        string birthLoc, 
                        string skl1kind, 
                        string skl2kind, 
                        string centOPS, 
                        string shopOPS, 
                        string shopRCVkind, 
                        byte centCanADD, 
                        byte centCanRWT, 
                        byte centCanDEL, 
                        byte shopCanADD, 
                        byte shopCanRWT, 
                        byte shopCanDEL, 
                        string opis) {
                skyruleRow rowskyruleRow = ((skyruleRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        recID,
                        addTS,
                        modTS,
                        addUID,
                        modUID,
                        lanSrvID,
                        lanRecID,
                        origRecID,
                        recVer,
                        arAction,
                        arTS,
                        arUID,
                        record,
                        documTT,
                        birthLoc,
                        skl1kind,
                        skl2kind,
                        centOPS,
                        shopOPS,
                        shopRCVkind,
                        centCanADD,
                        centCanRWT,
                        centCanDEL,
                        shopCanADD,
                        shopCanRWT,
                        shopCanDEL,
                        opis};
                rowskyruleRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowskyruleRow);
                return rowskyruleRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public skyruleRow FindByrecID(uint recID) {
                return ((skyruleRow)(this.Rows.Find(new object[] {
                            recID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                skyruleDataTable cln = ((skyruleDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new skyruleDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnrecID = base.Columns["recID"];
                this.columnaddTS = base.Columns["addTS"];
                this.columnmodTS = base.Columns["modTS"];
                this.columnaddUID = base.Columns["addUID"];
                this.columnmodUID = base.Columns["modUID"];
                this.columnlanSrvID = base.Columns["lanSrvID"];
                this.columnlanRecID = base.Columns["lanRecID"];
                this.columnorigRecID = base.Columns["origRecID"];
                this.columnrecVer = base.Columns["recVer"];
                this.columnarAction = base.Columns["arAction"];
                this.columnarTS = base.Columns["arTS"];
                this.columnarUID = base.Columns["arUID"];
                this.columnrecord = base.Columns["record"];
                this.columndocumTT = base.Columns["documTT"];
                this.columnbirthLoc = base.Columns["birthLoc"];
                this.columnskl1kind = base.Columns["skl1kind"];
                this.columnskl2kind = base.Columns["skl2kind"];
                this.columncentOPS = base.Columns["centOPS"];
                this.columnshopOPS = base.Columns["shopOPS"];
                this.columnshopRCVkind = base.Columns["shopRCVkind"];
                this.columncentCanADD = base.Columns["centCanADD"];
                this.columncentCanRWT = base.Columns["centCanRWT"];
                this.columncentCanDEL = base.Columns["centCanDEL"];
                this.columnshopCanADD = base.Columns["shopCanADD"];
                this.columnshopCanRWT = base.Columns["shopCanRWT"];
                this.columnshopCanDEL = base.Columns["shopCanDEL"];
                this.columnopis = base.Columns["opis"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnrecID = new global::System.Data.DataColumn("recID", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrecID);
                this.columnaddTS = new global::System.Data.DataColumn("addTS", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnaddTS);
                this.columnmodTS = new global::System.Data.DataColumn("modTS", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmodTS);
                this.columnaddUID = new global::System.Data.DataColumn("addUID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnaddUID);
                this.columnmodUID = new global::System.Data.DataColumn("modUID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmodUID);
                this.columnlanSrvID = new global::System.Data.DataColumn("lanSrvID", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlanSrvID);
                this.columnlanRecID = new global::System.Data.DataColumn("lanRecID", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlanRecID);
                this.columnorigRecID = new global::System.Data.DataColumn("origRecID", typeof(uint), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnorigRecID);
                this.columnrecVer = new global::System.Data.DataColumn("recVer", typeof(ushort), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrecVer);
                this.columnarAction = new global::System.Data.DataColumn("arAction", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnarAction);
                this.columnarTS = new global::System.Data.DataColumn("arTS", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnarTS);
                this.columnarUID = new global::System.Data.DataColumn("arUID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnarUID);
                this.columnrecord = new global::System.Data.DataColumn("record", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrecord);
                this.columndocumTT = new global::System.Data.DataColumn("documTT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndocumTT);
                this.columnbirthLoc = new global::System.Data.DataColumn("birthLoc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbirthLoc);
                this.columnskl1kind = new global::System.Data.DataColumn("skl1kind", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnskl1kind);
                this.columnskl2kind = new global::System.Data.DataColumn("skl2kind", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnskl2kind);
                this.columncentOPS = new global::System.Data.DataColumn("centOPS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncentOPS);
                this.columnshopOPS = new global::System.Data.DataColumn("shopOPS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshopOPS);
                this.columnshopRCVkind = new global::System.Data.DataColumn("shopRCVkind", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshopRCVkind);
                this.columncentCanADD = new global::System.Data.DataColumn("centCanADD", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncentCanADD);
                this.columncentCanRWT = new global::System.Data.DataColumn("centCanRWT", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncentCanRWT);
                this.columncentCanDEL = new global::System.Data.DataColumn("centCanDEL", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncentCanDEL);
                this.columnshopCanADD = new global::System.Data.DataColumn("shopCanADD", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshopCanADD);
                this.columnshopCanRWT = new global::System.Data.DataColumn("shopCanRWT", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshopCanRWT);
                this.columnshopCanDEL = new global::System.Data.DataColumn("shopCanDEL", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshopCanDEL);
                this.columnopis = new global::System.Data.DataColumn("opis", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnopis);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnrecID}, true));
                this.columnrecID.AllowDBNull = false;
                this.columnrecID.Unique = true;
                this.columnaddTS.AllowDBNull = false;
                this.columnmodTS.AllowDBNull = false;
                this.columnaddUID.AllowDBNull = false;
                this.columnaddUID.MaxLength = 16;
                this.columnmodUID.AllowDBNull = false;
                this.columnmodUID.MaxLength = 16;
                this.columnlanSrvID.AllowDBNull = false;
                this.columnlanRecID.AllowDBNull = false;
                this.columnorigRecID.AllowDBNull = false;
                this.columnrecVer.AllowDBNull = false;
                this.columnarAction.AllowDBNull = false;
                this.columnarAction.MaxLength = 8;
                this.columnarTS.AllowDBNull = false;
                this.columnarUID.AllowDBNull = false;
                this.columnarUID.MaxLength = 16;
                this.columnrecord.AllowDBNull = false;
                this.columnrecord.MaxLength = 16;
                this.columndocumTT.AllowDBNull = false;
                this.columndocumTT.MaxLength = 3;
                this.columnbirthLoc.AllowDBNull = false;
                this.columnbirthLoc.MaxLength = 4;
                this.columnskl1kind.AllowDBNull = false;
                this.columnskl1kind.MaxLength = 8;
                this.columnskl2kind.AllowDBNull = false;
                this.columnskl2kind.MaxLength = 8;
                this.columncentOPS.AllowDBNull = false;
                this.columncentOPS.MaxLength = 14;
                this.columnshopOPS.AllowDBNull = false;
                this.columnshopOPS.MaxLength = 14;
                this.columnshopRCVkind.AllowDBNull = false;
                this.columnshopRCVkind.MaxLength = 13;
                this.columncentCanADD.AllowDBNull = false;
                this.columncentCanRWT.AllowDBNull = false;
                this.columncentCanDEL.AllowDBNull = false;
                this.columnshopCanADD.AllowDBNull = false;
                this.columnshopCanRWT.AllowDBNull = false;
                this.columnshopCanDEL.AllowDBNull = false;
                this.columnopis.AllowDBNull = false;
                this.columnopis.MaxLength = 128;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public skyruleRow NewskyruleRow() {
                return ((skyruleRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new skyruleRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(skyruleRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.skyruleRowChanged != null)) {
                    this.skyruleRowChanged(this, new skyruleRowChangeEvent(((skyruleRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.skyruleRowChanging != null)) {
                    this.skyruleRowChanging(this, new skyruleRowChangeEvent(((skyruleRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.skyruleRowDeleted != null)) {
                    this.skyruleRowDeleted(this, new skyruleRowChangeEvent(((skyruleRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.skyruleRowDeleting != null)) {
                    this.skyruleRowDeleting(this, new skyruleRowChangeEvent(((skyruleRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveskyruleRow(skyruleRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DS_findSkyRule ds = new DS_findSkyRule();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "skyruleDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class skyruleRow : global::System.Data.DataRow {
            
            private skyruleDataTable tableskyrule;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal skyruleRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableskyrule = ((skyruleDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint recID {
                get {
                    return ((uint)(this[this.tableskyrule.recIDColumn]));
                }
                set {
                    this[this.tableskyrule.recIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime addTS {
                get {
                    return ((global::System.DateTime)(this[this.tableskyrule.addTSColumn]));
                }
                set {
                    this[this.tableskyrule.addTSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime modTS {
                get {
                    return ((global::System.DateTime)(this[this.tableskyrule.modTSColumn]));
                }
                set {
                    this[this.tableskyrule.modTSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string addUID {
                get {
                    return ((string)(this[this.tableskyrule.addUIDColumn]));
                }
                set {
                    this[this.tableskyrule.addUIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string modUID {
                get {
                    return ((string)(this[this.tableskyrule.modUIDColumn]));
                }
                set {
                    this[this.tableskyrule.modUIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint lanSrvID {
                get {
                    return ((uint)(this[this.tableskyrule.lanSrvIDColumn]));
                }
                set {
                    this[this.tableskyrule.lanSrvIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint lanRecID {
                get {
                    return ((uint)(this[this.tableskyrule.lanRecIDColumn]));
                }
                set {
                    this[this.tableskyrule.lanRecIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public uint origRecID {
                get {
                    return ((uint)(this[this.tableskyrule.origRecIDColumn]));
                }
                set {
                    this[this.tableskyrule.origRecIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public ushort recVer {
                get {
                    return ((ushort)(this[this.tableskyrule.recVerColumn]));
                }
                set {
                    this[this.tableskyrule.recVerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string arAction {
                get {
                    return ((string)(this[this.tableskyrule.arActionColumn]));
                }
                set {
                    this[this.tableskyrule.arActionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime arTS {
                get {
                    return ((global::System.DateTime)(this[this.tableskyrule.arTSColumn]));
                }
                set {
                    this[this.tableskyrule.arTSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string arUID {
                get {
                    return ((string)(this[this.tableskyrule.arUIDColumn]));
                }
                set {
                    this[this.tableskyrule.arUIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string record {
                get {
                    return ((string)(this[this.tableskyrule.recordColumn]));
                }
                set {
                    this[this.tableskyrule.recordColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string documTT {
                get {
                    return ((string)(this[this.tableskyrule.documTTColumn]));
                }
                set {
                    this[this.tableskyrule.documTTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string birthLoc {
                get {
                    return ((string)(this[this.tableskyrule.birthLocColumn]));
                }
                set {
                    this[this.tableskyrule.birthLocColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string skl1kind {
                get {
                    return ((string)(this[this.tableskyrule.skl1kindColumn]));
                }
                set {
                    this[this.tableskyrule.skl1kindColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string skl2kind {
                get {
                    return ((string)(this[this.tableskyrule.skl2kindColumn]));
                }
                set {
                    this[this.tableskyrule.skl2kindColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string centOPS {
                get {
                    return ((string)(this[this.tableskyrule.centOPSColumn]));
                }
                set {
                    this[this.tableskyrule.centOPSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string shopOPS {
                get {
                    return ((string)(this[this.tableskyrule.shopOPSColumn]));
                }
                set {
                    this[this.tableskyrule.shopOPSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string shopRCVkind {
                get {
                    return ((string)(this[this.tableskyrule.shopRCVkindColumn]));
                }
                set {
                    this[this.tableskyrule.shopRCVkindColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public byte centCanADD {
                get {
                    return ((byte)(this[this.tableskyrule.centCanADDColumn]));
                }
                set {
                    this[this.tableskyrule.centCanADDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public byte centCanRWT {
                get {
                    return ((byte)(this[this.tableskyrule.centCanRWTColumn]));
                }
                set {
                    this[this.tableskyrule.centCanRWTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public byte centCanDEL {
                get {
                    return ((byte)(this[this.tableskyrule.centCanDELColumn]));
                }
                set {
                    this[this.tableskyrule.centCanDELColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public byte shopCanADD {
                get {
                    return ((byte)(this[this.tableskyrule.shopCanADDColumn]));
                }
                set {
                    this[this.tableskyrule.shopCanADDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public byte shopCanRWT {
                get {
                    return ((byte)(this[this.tableskyrule.shopCanRWTColumn]));
                }
                set {
                    this[this.tableskyrule.shopCanRWTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public byte shopCanDEL {
                get {
                    return ((byte)(this[this.tableskyrule.shopCanDELColumn]));
                }
                set {
                    this[this.tableskyrule.shopCanDELColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string opis {
                get {
                    return ((string)(this[this.tableskyrule.opisColumn]));
                }
                set {
                    this[this.tableskyrule.opisColumn] = value;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class skyruleRowChangeEvent : global::System.EventArgs {
            
            private skyruleRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public skyruleRowChangeEvent(skyruleRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public skyruleRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591